# needs superuser permissions
sudo: required
language: generic

services:
    - docker

# in order to run the test suite, we need to run the dev build
before_install:
    - docker build -t callistachang/docker-react -f Dockerfile.dev .

# -- --coverage prevents the test suite from taking input
script:
    - docker run -e CI=true callistachang/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-us-east-2-804847848812"
    bucket_path: "docker-react" #same as the app
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY